fa-brands fa-hacker-news
fa-brands fa-github
fa-brands fa-bluesky
fa-brands fa-linkedin
fa-brands fa-instagram
fa-solid fa-circle-info
fa-solid fa-right-from-bracket
fa-solid fa-users
fa-solid fa-house
fa-solid fa-down-left-and-up-right-to-center
fa-solid fa-up-right-and-down-left-from-center
fa-solid fa-camera-retro
fa-solid fa-camera-rotate
fa-solid fa-link