fa-brands fa-hacker-news
fa-brands fa-github
fa-brands fa-bluesky
fa-brands fa-twitter
fa-brands fa-linkedin
fa-brands fa-instagram
fa-solid fa-circle-info
fa-solid fa-right-from-bracket
fa-solid fa-users
fa-solid fa-house
fa-solid fa-down-left-and-up-right-to-center
fa-solid fa-up-right-and-down-left-from-center
fa-solid fa-camera-retro
fa-solid fa-camera-rotate
fa-solid fa-link
fa-solid fa-circle-xmark
fa-solid fa-file-signature
fa-solid fa-cloud-arrow-up
fa-solid fa-images
fa-solid fa-bars
fa-solid fa-arrow-down-wide-short
fa-solid fa-arrows-spin
fa-solid fa-rotate-right
fa-solid fa-code-branch
fa-solid fa-code-merge
fa-solid fa-code-compare
fa-solid fa-code-commit
fa-solid fa-code-pull-request
fa-solid fa-arrow-up-wide-short
fa-solid fa-arrow-down-wide-short
fa-solid fa-rotate
fa-solid fa-rotate-right
fa-solid fa-arrows-spin
fa-solid fa-earth-asia